//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenizCafe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrators
    {
        public byte AdminId { get; set; }
        public string AdminName { get; set; }
        public string AdminSurname { get; set; }
        public string AdminUserName { get; set; }
        public string AdminPassword { get; set; }
        public bool AdminIsActive { get; set; }
    }
}
