//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DenizCafe.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLines
    {
        public int OrderLineId { get; set; }
        public byte OrderLineProductCount { get; set; }
        public decimal OrderLineTotal { get; set; }
        public System.DateTime OrderLineDate { get; set; }
        public int ProductId { get; set; }
        public int OrderId { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
